
name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.10'

     - name: Skip Install Dependencies
       run: echo "No requirements file yet, skipping pip install"

     - name: Skip Test Execution
       run: echo "no pytest, skip testing for now"

     - name: Login to docker hub
       uses: docker/login-action@v3
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build docker image
       run: docker build -t techietech/my-app-image:latest .

     - name: Run container to verify output
       run: docker run --rm techietech/my-app-image:latest .

     - name: Push docker image to Docker Hub
       run: docker push techietech/my-app-image:latest

